---
title: "Blog"
baseurl: ""
url: "https://m4u5r4n5.github.io/my-blog/" 

defaults:
  - scope:
      path: "_posts"
    values:
      layout: post

markdown: kramdown
highlighter: rouge
permalink: /my-blog/:year/:month/:day/:title/
---
